# Google Cloud App Engine Configuration
# Deploy with: gcloud app deploy

runtime: python39
env: standard

entrypoint: gunicorn -w 4 -b 0.0.0.0:$PORT wsgi:app

env_variables:
  FLASK_ENV: "production"
  FLASK_DEBUG: "0"

automatic_scaling:
  min_instances: 1
  max_instances: 10

handlers:
- url: .*
  script: auto
  secure: always
  redirect_http_response_code: 301
